### ISSUE TITLE
Reusing a ZFS dataset name breaks zrepl replication.

### ISSUE THREAD

**Issue by Crest** [zrepl/zrepl#825] opened 2024-10-08 12:34 UTC
The following steps break zrepl replication:

1. Create a ZFS filesystem matched by a zrepl job.
2. Wait for zrepl to snapshot and replicate it.
3. Destroy the filesystem at the source.
4. Create a new filesystem with the same name.
5. Wait for zrepl to snapshot and attempt to replicate it.

During the last step zrepl will snapshot the new dataset, but replication can not succeed since obviously the new dataset won't have any valid starting point form which to (incrementally) send and receive.

Neither destroying the conflicting dataset at the sink nor leaving replication broken is sane or user-friendly. In my opinion the least bad option would be to rename the conflicting old dataset out of the way (e.g. append a generation/conflict counter to its name), but its snapshots should probably still be counted when it comes to snapshot retention and if no snapshots remain the dataset should be garbage collected.

**Comment by gdevenyi** [comment] 2024-10-08 22:35
To be honest this seems like the most sensible thing here. A manual intervention was done (destroying the old dataset), so a manual intervention should be needed to fix this on the sink side.

My issue remains the documentation on handling these situation is lacking (c/f #814 )

**Comment by Crest** [comment] 2024-10-09 11:33
My use-case is a FreeBSD jail host with (at least) one ZFS filesystem per jail. To keep things simple the filesystem name is derived from the jail name (`$pool/jails/$name`). I replace most jail file systems to atomically update the jails, but want to keep their names. As it stands zrepl can't backup such a system without disgusting workarounds like adding a generation counter to the filesystem name and setting a manual mountpoint on the source system.

**Comment by InsanePrawn** [comment] 2024-10-12 17:30
This is a duplicate of long-standing issues https://github.com/zrepl/zrepl/issues/70#issuecomment-694991085 and #426. 

I agree with @gdevenyi that describing having to clean up your datasets as "not sane" is questionable.
I understand where you're coming from, but blindly deleting the conflicting backups would be much more "not sane" in zrepl's opinion.

We would all like some sort of (ideally garbage-collected) "recycle bin" for conflicting datasets (it's in the linked comment to issue 70, see also #408 for All The conflict resolutions) - but someone has to implement it first.
Sadly, Christian has limited time and I suck at Go or arguably at coding.

Closing as duplicate.

**Closed by InsanePrawn** 2024-10-12 17:30 UTC
