### ISSUE TITLE
How to sync all "manual" snapshots in order?

### ISSUE THREAD

**Issue by tdschmidl** [zrepl/zrepl#244] opened 2019-11-11 19:33 UTC
Hi all,

we are using zrepl on some of our ZFS Backup systems very successfully so far, so a big thumbs up first of all!

For my recent project I have an existing ZFS backup server, where I want to migrate all snapshots from to a new machine.
I've setup zrepl in pull & source mode and was able to start the sync - but noticed, that zrepl only greps the last snapshot, which was created and not the previous ones.
Am I missing here something?

Configs:
Pull side:
```
jobs:
- name: pull_source
  type: source
  serve:
   [..] cutted, not relevant
  filesystems: {
    "storage/zfsbackup-local-backup<": true
  }
  snapshotting:
    type: manual
```

Source side snapshots:
```root@zfsbackup ~ # zfs list -t all -d99 storage/zfsbackup-local-backup
NAME                                                     CREATION
storage/zfsbackup-local-backup                           Tue Oct 29 18:16 2019
storage/zfsbackup-local-backup@2019-10-19-DebianJessie   Tue Oct 29 19:59 2019
storage/zfsbackup-local-backup@2019-10-19-DebianStretch  Tue Oct 29 21:48 2019
storage/zfsbackup-local-backup#zrepl_replication_cursor  Tue Oct 29 21:48 2019
```

synced by zrepl on pull side:
```
storage/zrepl_pull/storage/zfsbackup-local-backup                           Mon Nov 11 20:32 2019
storage/zrepl_pull/storage/zfsbackup-local-backup@2019-10-19-DebianStretch  Tue Oct 29 21:48 2019
```

zrepl journalctl log:
```
Nov 11 20:32:00 zfsbackup zrepl[8308]: [pull][repl]: conflict invocation="1" filesystem="storage/zfsbackup-local-backup" conflict="no common snapshot or suitable bookmark between sender and receiver:\n  sorted sender versions:\n    @2019-10-19-DebianJessie\n    @2019-10-19-DebianStretch\n  sorted receiver versions:\n"
Nov 11 20:32:00 zfsbackup zrepl[8308]: [pull][repl]: automatically resolved filesystem="storage/zfsbackup-local-backup" resolution="start replication at most recent snapshot @2019-10-19-DebianStretch" invocation="1"
```

**Comment by problame** [comment] 2019-11-12 20:27
> I've setup zrepl in pull & source mode and was able to start the sync - but noticed, that zrepl only greps the last snapshot, which was created and not the previous ones.
Am I missing here something?

No, this works as intended: currently, the only implemented conflict resolution policy for an empty receiver is to start at the most recent snapshot.

This is a duplicate of #187. 

The code that handles these cases is in `func resolveConflict`:

https://github.com/zrepl/zrepl/blob/f9c7766073865ae2590fb2393e3c3ca447b7022f/replication/logic/replication_logic.go#L312

https://github.com/zrepl/zrepl/blob/f9c7766073865ae2590fb2393e3c3ca447b7022f/replication/logic/replication_logic.go#L210-L228

Changing the hard-coded policy from `most recent` to `all` should be a straight-forward patch, however, a proper solution would make this configurable, which is a little more effort.

I might get to this after completing #218 and #217, both of which are going to introduce replication configuration. Above policy will also be configured in that configuration object.

If you are willing to fund development of this feature, please consider [supporting zrepl](https://zrepl.github.io/supporters.html) or [post a bounty on issue 187](https://www.bountysource.com/issues/75577879-initial-replication-make-policy-configurable)

**Closed by problame** 2019-11-12 20:27 UTC
