### ISSUE TITLE
[feature request] ability to disable a job

### ISSUE THREAD

**Issue by eoli3n** [zrepl/zrepl#559] opened 2022-01-16 20:13 UTC
I would like to be able to disable a specific job.
```bash
$ zrepl disable sync_to_nas
```
The usecase is when I'm connected to a network (4G/5G) with data limitations, I want to be able to disable sync on the server and reenabled it when connected to a unlimited wifi network.

**Comment by InsanePrawn** [comment] 2022-01-18 00:44
Duplicate of #42 and  #333.

**Closed by InsanePrawn** 2022-01-18 00:44 UTC
