### ISSUE TITLE
noise from closing tcp+tls connection on FreeBSD

### ISSUE THREAD

**Issue by avg-I** [zrepl/zrepl#190] opened 2019-06-24 06:34 UTC
Frequently, but not always, I see these messages logged at the end of a push session:
```
zrepl[1061]: 2019-06-24T04:52:16Z [ERRO][backup]: error closing connection subsystem="rpc.data" invocation="16" err="close tcp 192.168.0.251:15884->192.168.0.88:7888: connection reset by peer"
zrepl[1062]: job=backup subsystem=rpc.data msg="error closing connection" invocation=16 err="close tcp 192.168.0.251:15884->192.168.0.88:7888: connection reset by peer"
```
It looks like some sort of a race between the two ends of the connection.
Maybe the issue is specific to FreeBSD (or even my particular version of FreeBSD).

**Comment by problame** [comment] 2019-06-29 09:36
Could you please provide more information on the network link?
What OSes (and versions) on either side? I assume FreeBSD.
TCP transport or TLS transport?
What is the round-trip time between the systems?
What is the bandwidth on the link?
Pull or push job?

**Comment by problame** [comment] 2019-06-29 09:40
Oh, and if you are really motivated: look into `rpc/dataconn/timeoutconn/internal/wireevaluator/wireevaluator.go` and try to run it on your system for your transport:
It's an integration test of the zrepl transport stack's closing semantics.

**Comment by avg-I** [comment] 2019-07-01 14:13
Yes, it's FreeBSD on both sides. One is 12 and the other is 13 (CURRENT).
They are both on the same 1 Gbit LAN.
```.yaml
jobs:
  - name: backup
    type: push
    connect:
      type: tls
```

**Comment by mdtancsa** [comment] 2019-07-15 17:04
Hi there, I see the same issue periodically. In one case a FreeBSD RELENG_11 pushing to RELENG_12- 1 out of 142 sessions gave such an error.  Nothing is logged on the backup server that I am pushing to. The client is also TLS over gigabit and streams out at about 600Mb/s to a backup server thats on a 10G nic.
On another server a bit more frequent. 
all.log.0.bz2:Jul 14 06:24:02 zrepl[814]: 2019-07-14T06:24:02-04:00 [ERRO][self_to_backup4c]: error closing connection invocation="1040" subsystem="rpc.data" err="close tcp xx.yy.zz.9:59189->xx.yy.zz.254:9888: connection reset by peer"
all.log.1.bz2:Jul 13 13:23:54 zrepl[814]: 2019-07-13T13:23:54-04:00 [ERRO][self_to_backup4c]: error closing connection invocation="972" subsystem="rpc.data" err="close tcp xx.yy.zz.9:59180->xx.yy.zz.254:9888: connection reset by peer"
all.log.2.bz2:Jul 12 09:38:50 zrepl[814]: 2019-07-12T09:38:50-04:00 [ERRO][self_to_backup4c]: error closing connection subsystem="rpc.data" invocation="861" err="close tcp xx.yy.zz.9:49757->xx.yy.zz.254:9888: connection reset by peer"
all.log.2.bz2:Jul 12 10:53:48 zrepl[814]: 2019-07-12T10:53:48-04:00 [ERRO][self_to_backup4c]: error closing connection err="close tcp xx.yy.zz.9:55941->xx.yy.zz.254:9888: connection reset by peer" invocation="866" subsystem="rpc.data"
all.log.2.bz2:Jul 12 18:38:54 zrepl[814]: 2019-07-12T18:38:54-04:00 [ERRO][self_to_backup4c]: error closing connection invocation="897" subsystem="rpc.data" err="close tcp xx.yy.zz.9:33122->xx.yy.zz.254:9888: connection reset by peer"
all.log.3.bz2:Jul 11 13:53:38 zrepl[814]: 2019-07-11T13:53:38-04:00 [ERRO][self_to_backup4c]: error closing connection err="close tcp xx.yy.zz.9:58311->xx.yy.zz.254:9888: connection reset by peer" invocation="782" subsystem="rpc.data"
all.log.5.bz2:Jul  9 12:53:24 zrepl[814]: 2019-07-09T12:53:24-04:00 [ERRO][self_to_backup4c]: error closing connection err="close tcp xx.yy.zz.9:51657->xx.yy.zz.254:9888: connection reset by peer" invocation="586" subsystem="rpc.data"

**Comment by problame** [comment] 2019-07-15 22:59
I tried to replicate the problem between two VMs runinng 12.0-RELEASE.
I generated artificial snapshots with real payload to give TCP some time to widen the flow / congestion control window.
I also tried to simulate real network condition by using Linux `tc-netem` on the virtual NIC (from the hypervisor).

I cannot reproduce the issue, but I am seeing it on my personal deployment (both FreeBSD 12) occassionally.

As mentioned above, `rpc/dataconn/timeoutconn/internal/wireevaluator/wireevaluator.go` contains an under-documented stress test for the transport layer's connection teardown behavior.

**Comment by mdtancsa** [comment] 2019-07-16 13:56
Thanks for looking into it!  I guess ultimately, is this an error condition I need to worry about ? The daemons seem to recover ok in the end

**Comment by problame** [comment] 2019-07-17 19:06
I spun up two DigitalOcean instances to see if a real network helps reproducing the issue, and within a 3 hour window, the error message occurred once.

I am 90% sure the errno = ECONNRESET stems from this function in the kernel:

https://github.com/freebsd/freebsd/blob/f80b423863fc615ceba1005e795297bcd697eaa9/sys/kern/uipc_socket.c#L1073-L1110

Specifically, the call to `sodisconnect`:

https://github.com/freebsd/freebsd/blob/f80b423863fc615ceba1005e795297bcd697eaa9/sys/kern/uipc_socket.c#L1256-L1268

which calls the pru_disconnect fptr, which is a ptr to `tcp_disconnect` in this case:

https://github.com/freebsd/freebsd/blob/f80b423863fc615ceba1005e795297bcd697eaa9/sys/netinet/tcp_usrreq.c#L676-L704

Where ECONNRESET is returned at exactly one line.

Anyways, in that particular situation, I guess it's ok to ignore the error in zrepl.
We generally log `close()` errors because, in theory, an unsuccessful cluse might constitute an FD leak, and the log output would provide means to debug it.
But it isn't a leak in this case, so you don't need to worry about it.

**Comment by problame** [comment] 2019-09-27 12:10
@avg-I @mdtancsa could you please try the CI-build of 50a7c21 by downloading the CI artifact and replacing /usr/local/bin/zrepl with it?
The Go 1.11 build failed due to bad CI config, Go 1.12 and Go 1.13 (preferred) should work fine.

![image](https://user-images.githubusercontent.com/956573/65768184-85bdd080-e130-11e9-9789-d3c77f6af752.png)


Please report back ASAP, so we can get this fix into the upcoming release.

**Comment by mdtancsa** [comment] 2019-09-27 13:14
Hi, I can give it a try on Monday!  Thanks very much!

**Closed** 2019-09-28 11:33 UTC
Labels: bug, impl

**Comment by problame** [comment] 2019-09-28 11:34
@mdtancsa fix was confirmed by @avg-I , committing this now because we want to have a zrepl 0.2 RC1 out this weekend

**Comment by mdtancsa** [comment] 2019-10-04 14:31
I have been running this version for a few days now as well and all
looks good with this issue.

Thanks!

    ---Mike
