### ISSUE TITLE
Second replication begins if first replication is not finished

### ISSUE THREAD

**Issue by woodsb02** [zrepl/zrepl#8] opened 2017-10-01 10:20 UTC
During first replication of many Gigabytes of data, I initially had the interval of the pull job set as 10m, and the first replication would not be finished by the time the second one was called to start. I checked the status many hours later and could see numerous ssh sessions running which led me to believe multiple replication jobs were now running at once (which I dont think should ever happen). I expected that if another replication job was called to start before the previous had finished, the new job would just be cancelled entirely.

I did not look into the state of my replicated data, or if the replications were proceeding ok. It was purely the fact that multiple zrepl ssh sessions were running that led me to believe this was the behaviour.

**Comment by problame** [comment] 2017-10-02 17:18
This is a bug. WIll fix.

**Comment by problame** [comment] 2017-10-05 16:46
So I guess this was a pull job? I cannot reproduce the issue.

`cmd/config_job_pull.go:94 JobStart()` is strictly sequential and will not reconnect unless the previous pull finished.

What's still an open issue: where did all the dangling ssh sessions come from?

**Comment by woodsb02** [comment] 2017-10-05 23:14
I will try to replicate it this weekend, and will report back on my findings. I didn’t spend the time to investigate and record my findings last time... I just remember seeing numerous lines from “sudo pgrep -lf zrepl”

**Comment by problame** [comment] 2017-10-16 20:00
Were you able to replicate the described behavior?

**Comment by problame** [comment] 2017-11-04 10:23
OK, I was able to observer the issue on a testing system. I saw lots of defunct processes, most likely ssh processes that timed out but were not `waitpid()` for by zrepl.
Sadly, the logs are gone because the testing system was also used to test TCP logger, which doesn't handle timeouts on the connection well, see #26

**Comment by problame** [comment] 2018-02-16 20:13
So I think I fixed the issue in 6b5bd0a43c449fc916c105db42e1b67364d609a1 --- it just landed in zrepl master. 
Are you in a situation where you can just build zrepl master and check if the issue is resolved?

**Comment by woodsb02** [comment] 2018-03-04 02:52
Hi Christian,
Yes, you are correct - this issue was the same as the one reported in #56.
I have just finished testing with the new latest (unreleased) version of zrepl, and can confirm this is now fixed.
Thanks for your work on fixing this!
Cheers,
Ben

**Closed** 2018-03-04 14:31 UTC
Labels: bug
