### ISSUE TITLE
panic: 'cannot close send stream' / 'active child tasks'

### ISSUE THREAD

**Issue by mihav** [zrepl/zrepl#457] opened 2021-04-05 20:37 UTC
Hello,

I'm currently testing zrepl on few servers. I've got a few servers setup as type source and stdinserver and one server which pulls from them via ssh+stdinserver.

zrepl on one of the source servers occasionally crashes with the following message:
```
zrepl[1015232]: panic: end task: 1 active child tasks
zrepl[1015232]: : end task: task still has active child tasks
zrepl[1015232]: goroutine 8267229 [running]:
zrepl[1015232]: github.com/zrepl/zrepl/daemon/logging/trace.WithTask.func1.1(0xc000565a70, 0x558a1a45a200)
zrepl[1015232]:         github.com/zrepl/zrepl/daemon/logging/trace/trace.go:249 +0x6be
zrepl[1015232]: github.com/zrepl/zrepl/daemon/logging/trace.WithTask.func1()
zrepl[1015232]:         github.com/zrepl/zrepl/daemon/logging/trace/trace.go:272 +0x3a
zrepl[1015232]: github.com/zrepl/zrepl/daemon/logging/trace.WithTaskAndSpan.func1()
zrepl[1015232]:         github.com/zrepl/zrepl/daemon/logging/trace/trace_convenience.go:41 +0x39
zrepl[1015232]: github.com/zrepl/zrepl/daemon/job.(*PassiveSide).Run.func1(0x558a1a47e7d8, 0xc00053d680, 0x558a1a4767c8, 0xc0001f75a0, 0xc00053d5f0)
zrepl[1015232]:         github.com/zrepl/zrepl/daemon/job/passive.go:179 +0x2de
zrepl[1015232]: github.com/zrepl/zrepl/rpc.NewServer.func1.1(0x558a1a47e7d8, 0xc00053d5c0, 0x558a1a476818, 0xc0001f7580, 0xc00053d5f0)
zrepl[1015232]:         github.com/zrepl/zrepl/rpc/rpc_server.go:56 +0xd7
zrepl[1015232]: github.com/zrepl/zrepl/rpc/grpcclientidentity.NewInterceptors.func1(0x558a1a47e7d8, 0xc00053d5c0, 0x558a1a3b4260, 0xc000032c00, 0xc0001f7440, 0xc0000a09d8, 0xc00005dba0, 0x558a19ac4988, 0x558a1a3eb800, 0xc00053d500)
zrepl[1015232]:         github.com/zrepl/zrepl/rpc/grpcclientidentity/authlistener_grpc_adaptor.go:136 +0x464
zrepl[1015232]: github.com/zrepl/zrepl/replication/logic/pdu._Replication_ReplicationCursor_Handler(0x558a1a402740, 0xc00009efc0, 0x558a1a47e7d8, 0xc00053d500, 0xc00054b920, 0xc000200570, 0x558a1a47e7d8, 0xc00053d500, 0xc00043e840, 0x12)
zrepl[1015232]:         github.com/zrepl/zrepl/replication/logic/pdu/pdu_grpc.pb.go:226 +0x150
zrepl[1015232]: google.golang.org/grpc.(*Server).processUnaryRPC(0xc00022e000, 0x558a1a4869f8, 0xc00099e180, 0xc000aa6300, 0xc0002006c0, 0x558a1a8948e0, 0x0, 0x0, 0x0)
zrepl[1015232]:         google.golang.org/grpc@v1.35.0/server.go:1217 +0x52b
zrepl[1015232]: google.golang.org/grpc.(*Server).handleStream(0xc00022e000, 0x558a1a4869f8, 0xc00099e180, 0xc000aa6300, 0x0)
zrepl[1015232]:         google.golang.org/grpc@v1.35.0/server.go:1540 +0xd0c
zrepl[1015232]: google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0000b88f0, 0xc00022e000, 0x558a1a4869f8, 0xc00099e180, 0xc000aa6300)
zrepl[1015232]:         google.golang.org/grpc@v1.35.0/server.go:878 +0xad
zrepl[1015232]: created by google.golang.org/grpc.(*Server).serveStreams.func1
zrepl[1015232]:         google.golang.org/grpc@v1.35.0/server.go:876 +0x1fd
systemd[1]: zrepl.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
systemd[1]: zrepl.service: Failed with result 'exit-code'.
```
Any ideas? I'm using build from master branch on March 14th.

**Comment by InsanePrawn** [comment] 2021-04-06 14:41
Not sure if this could be a side effect of #424. @problame ?

What's your kernel version? 
Either way I'd recommend upgrading to current master, which is == 0.4rc2.

**Comment by mihav** [comment] 2021-04-06 16:33
Last crash was with 5.10.17 and ZFS 2.0.3, but it was crashing before with kernel 5.4. I'm using Arch linux. I'll bump it to latest tag and enable debug log. It may take some time to catch it though - sometimes it crashes after few days, last time it took 4 weeks. Weird thing is I got 4 source machines, all with same OS and only one crashes.

#424 doesn't seem quite the same as it looks like zrepl process was stalled for some reason and had to be killed manually. In my case deamon simply crashes and exits. There is no crashdump though. A workaround from #445 would help in my case, but that would only masque the bug.

**Comment by problame** [comment] 2021-04-06 17:16
> Not sure if this could be a symptom of #424. @problame ?
> 
> What's your kernel version? 
> Either way I'd recommend upgrading to current master, which is == 0.4rc2.

It's a separate issue.

**Comment by problame** [comment] 2021-04-07 06:47
It's most likely an issue with the ssh transport. I'll look into this this weekend. Has the issue always occured or only since a zrepl update?

**Comment by mihav** [comment] 2021-04-07 10:14
This happened with at least 0.3.1 when I created the setup and later when I bumped it to master from March 14th. I'm now running 0.4rc2 with debug logging enabled and waiting for it to happen again. Both of these machines are on a same subnet and it's reasonable to assume ssh session was not interrupted.

**Comment by mologie** [comment] 2021-08-30 13:52
This happened to me too, but with different config: I have host `a` and `b` connected via TLS transport over a semi-stable WireGuard connection. zrepl on `a` crashed once over the period of 1 month. I was not able to reproduce the issue since. Hope this info helps... at least we can say it's not exclusive to the SSH transport mechanism.

```
Aug 23 23:42:56 a zrepl[565094]: [b][rpc.data][Uv38$Fm6G$Fm6G.z2JH]: cannot close send stream err="<nil>"
Aug 23 23:43:03 a zrepl[565094]: [b][rpc.data][Uv38$Fm6G$Fm6G.z2JH]: cannot close send stream err="<nil>"
Aug 23 23:43:15 a zrepl[565094]: [b][rpc.data][Uv38$Fm6G$Fm6G.z2JH]: cannot close send stream err="<nil>"
Aug 23 23:43:23 a zrepl[565094]: [b][rpc.data][Uv38$Fm6G$Fm6G.z2JH]: cannot close send stream err="<nil>"
Aug 23 23:43:34 a zrepl[565094]: [b][rpc.data][Uv38$Fm6G$Fm6G.z2JH]: cannot close send stream err="<nil>"
Aug 23 23:43:41 a zrepl[565094]: [b][rpc.data][Uv38$Fm6G$Fm6G.z2JH]: cannot close send stream err="<nil>"
Aug 23 23:43:54 a zrepl[565094]: [b][rpc.data][Uv38$Fm6G$Fm6G.z2JH]: cannot close send stream err="<nil>"
Aug 23 23:44:02 a zrepl[565094]: [b][rpc.data][Uv38$Fm6G$Fm6G.z2JH]: cannot close send stream err="<nil>"
Aug 23 23:44:13 a zrepl[565094]: [b][rpc.data][Uv38$Fm6G$Fm6G.z2JH]: cannot close send stream err="<nil>"
Aug 23 23:44:20 a zrepl[565094]: [b][rpc.data][Uv38$Fm6G$Fm6G.z2JH]: cannot close send stream err="<nil>"
Aug 23 23:44:41 a zrepl[565094]: [b][rpc.data][Uv38$Fm6G$Fm6G.z2JH]: cannot close send stream err="<nil>"
Aug 23 23:48:39 a zrepl[565094]: [b][rpc.data][Uv38$Fm6G$Fm6G.z2JH]: cannot close send stream err="<nil>"
Aug 23 23:49:27 a zrepl[565094]: panic: end task: 1 active child tasks
Aug 23 23:49:27 a zrepl[565094]: : end task: task still has active child tasks
Aug 23 23:49:27 a zrepl[565094]: goroutine 2150998 [running]:
Aug 23 23:49:27 a zrepl[565094]: github.com/zrepl/zrepl/daemon/logging/trace.WithTask.func1.1(0xc00046cbd0, 0xee8b00)
Aug 23 23:49:27 a zrepl[565094]:         /src/daemon/logging/trace/trace.go:249 +0x65e
Aug 23 23:49:27 a zrepl[565094]: github.com/zrepl/zrepl/daemon/logging/trace.WithTask.func1()
Aug 23 23:49:27 a zrepl[565094]:         /src/daemon/logging/trace/trace.go:272 +0x38
Aug 23 23:49:27 a zrepl[565094]: github.com/zrepl/zrepl/daemon/logging/trace.WithTaskAndSpan.func1()
Aug 23 23:49:27 a zrepl[565094]:         /src/daemon/logging/trace/trace_convenience.go:41 +0x37
Aug 23 23:49:27 a zrepl[565094]: github.com/zrepl/zrepl/daemon/job.(*PassiveSide).Run.func1(0xfc76c0, 0xc000544ea0, 0xfbe0a0, 0xc00098cb40, 0xc000544e10)
Aug 23 23:49:27 a zrepl[565094]:         /src/daemon/job/passive.go:179 +0x2d5
Aug 23 23:49:27 a zrepl[565094]: github.com/zrepl/zrepl/rpc.NewServer.func1.1(0xfc76c0, 0xc000544de0, 0xfbe120, 0xc00098cb20, 0xc000544e10)
Aug 23 23:49:27 a zrepl[565094]:         /src/rpc/rpc_server.go:56 +0xd5
Aug 23 23:49:27 a zrepl[565094]: github.com/zrepl/zrepl/rpc/grpcclientidentity.NewInterceptors.func1(0xfc76c0, 0xc000544de0, 0xde22a0, 0xc0003daf00, 0xc00098c9c0, 0xc00098c9e0, 0xc000635ba0, 0x4a0946, 0xe1eac0, 0xc000544c00)
Aug 23 23:49:27 a zrepl[565094]:         /src/rpc/grpcclientidentity/authlistener_grpc_adaptor.go:136 +0x464
Aug 23 23:49:27 a zrepl[565094]: github.com/zrepl/zrepl/replication/logic/pdu._Replication_ReplicationCursor_Handler(0xe374c0, 0xc000200120, 0xfc76c0, 0xc000544c00, 0xc0008632c0, 0xc00037fd40, 0xfc76c0, 0xc000544c00, 0xc0003d0340, 0x10)
Aug 23 23:49:27 a zrepl[565094]:         /src/replication/logic/pdu/pdu_grpc.pb.go:226 +0x150
Aug 23 23:49:27 a zrepl[565094]: google.golang.org/grpc.(*Server).processUnaryRPC(0xc00023a000, 0xfd0780, 0xc000914900, 0xc0000b0100, 0xc0002183f0, 0x15043e0, 0x0, 0x0, 0x0)
Aug 23 23:49:27 a zrepl[565094]:         /go/pkg/mod/google.golang.org/grpc@v1.35.0/server.go:1217 +0x522
Aug 23 23:49:27 a zrepl[565094]: google.golang.org/grpc.(*Server).handleStream(0xc00023a000, 0xfd0780, 0xc000914900, 0xc0000b0100, 0x0)
Aug 23 23:49:27 a zrepl[565094]:         /go/pkg/mod/google.golang.org/grpc@v1.35.0/server.go:1540 +0xd05
Aug 23 23:49:27 a zrepl[565094]: google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0004f62a0, 0xc00023a000, 0xfd0780, 0xc000914900, 0xc0000b0100)
Aug 23 23:49:27 a zrepl[565094]:         /go/pkg/mod/google.golang.org/grpc@v1.35.0/server.go:878 +0xa5
Aug 23 23:49:27 a zrepl[565094]: created by google.golang.org/grpc.(*Server).serveStreams.func1
Aug 23 23:49:27 a zrepl[565094]:         /go/pkg/mod/google.golang.org/grpc@v1.35.0/server.go:876 +0x1fd
Aug 23 23:49:27 a systemd[1]: zrepl.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```

```
$ zrepl version
client: zrepl version=v0.4.0 go=go1.15.11 GOOS=linux GOARCH=amd64 Compiler=gc
server: zrepl version=v0.4.0 go=go1.15.11 GOOS=linux GOARCH=amd64 Compiler=gc

$ uname -srvpio
Linux 5.4.0-54-generic #60-Ubuntu SMP Fri Nov 6 10:37:59 UTC 2020 x86_64 x86_64 GNU/Linux

$ lsmod | ag '(zfs|lkp)'
lkp_Ubuntu_5_4_0_54_60_generic_80   118784  1
lkp_Ubuntu_5_4_0_54_60_generic_79   110592  1
lkp_Ubuntu_5_4_0_54_60_generic_78   106496  1
lkp_Ubuntu_5_4_0_54_60_generic_77    98304  1
lkp_Ubuntu_5_4_0_54_60_generic_76    98304  1
lkp_Ubuntu_5_4_0_54_60_generic_75    77824  1
lkp_Ubuntu_5_4_0_54_60_generic_74    32768  1
zfs                  4030464  50
```

**Comment by problame** [comment] 2021-09-19 16:42
I have pushed the above commit that fixes the error logging, i.e., 

```
Aug 23 23:48:39 a zrepl[565094]: [b][rpc.data][Uv38$Fm6G$Fm6G.z2JH]: cannot close send stream err="<nil>"
```

It'll be part of the next release, so if the error happens again, we know what was going on.

**Comment by problame** [comment] 2021-09-19 16:52
In essence, the idea in the `serveConnRequest` method is to log the close error, and then return anyways.
The assumption is that there's nothing we can do about a failed close except logging it.

And that'd be fine, _but_, we have a tracing framework in zrepl that keeps track of activities in the daemon.
It panics if a sub-activity (the open connection & associated helper goroutines) outlives its parent (`serveConnRequest`).

The env variable `ZREPL_TRACE_DEBUG_ENABLED` gates additional debug data collection for that subsystem.

https://github.com/zrepl/zrepl/blob/fecc9416aba93c3c533efd0e23aa3cc8b02cc78b/daemon/logging/trace/trace_debug.go#L10

It has a slight performance penalty, but probably bearable.
Could you please enable it on your systems so that we get more debug data on the next crash?

**Comment by problame** [comment] 2021-09-19 18:18
@mologie I also identified a bunch of missing `sendStream.Close` calls.
I created a branch/PR for the users that are affected of this bug.
Binary builds should be availabel from CI in a few minutes.
PR: (please subscribe for updates)  https://github.com/zrepl/zrepl/pull/519

**Comment by mologie** [comment] 2021-09-20 17:51
Ack, I will update my NAS's installation from the branch and set ZREPL_TRACE_DEBUG_ENABLED via the systemd service. Will have to cherry-pick my changes from #504 first.

Also subscribed to the PR, thanks! I have not seen another crash since I last posted, so I hope the software gods are kind to me and I can contribute some data.

**Comment by problame** [comment] 2021-09-25 19:41
> I have not seen another crash since I last posted, so I hope the software gods are kind to me and I can contribute some data.

@mologie to which non-occuring crash / PR are you referring here?

**Comment by mologie** [comment] 2021-09-25 22:12
> @mologie to which non-occuring crash / PR are you referring here?

The one of this issue -- I added details about [a single crash above](https://github.com/zrepl/zrepl/issues/457#issuecomment-908361569), but have not experienced this crash (or any other crash with zrepl at all) again since I posted about it.

**Comment by problame** [comment] 2021-12-12 12:04
Going to close this issue since #519 fixed a bunch of potential root causes.
It's going to be part of the (hopefully soon) next zrepl release.

**Closed by problame** 2021-12-12 12:04 UTC
Labels: bug
