### ISSUE TITLE
Reschedule planning when snapshot has been deleted by third party

### ISSUE THREAD

**Issue by Debilski** [zrepl/zrepl#471] opened 2021-04-19 14:41 UTC
When a snapshot is deleted after the planning step (for example by a third party snapshotting tool), zrepl generates a `STEP-ERROR` and stops processing this file system:

    STEP-ERROR (step 0/27, 0 B/16.5 KiB) validate send arguments: `To` invalid: dataset "MAIN/xy@hourly-2021-04-18-14" does not exist

All other file systems will sync just fine and eventually have a state of `DONE`. However, the failed file system will be stuck with this error until zrepl syncs for the next time, when – given long enough sync times – the same error could happen again.

Maybe it would make sense to detect in advance when a snapshot has vanished and simply ignore this, or automatically reschedule a planning step when this error occurs.

**Comment by problame** [comment] 2021-04-19 21:07
I think this is a duplicate of #349 ?

**Comment by problame** [comment] 2021-04-19 21:10
> Maybe it would make sense to detect in advance when a snapshot has vanished and simply ignore this, or automatically reschedule a planning step when this error occurs.

It's still racy to check in advance.
The reschedule is the basic idea in #349 .
The other idea is to add some zrepl-internal locking so that at least the pruning job is prevented from interfering with replication. But that has all sorts of implications with regards to distributed locking.

**Comment by Debilski** [comment] 2021-04-20 11:07
Yeah, #349 already covers my problem, I guess.

**Closed** 2021-06-15 16:45 UTC
Labels: analysis, duplicate, usability
