### ISSUE TITLE
zrepl killed by kernel OOM

### ISSUE THREAD

**Issue by MAFLO321** [zrepl/zrepl#423] opened 2021-02-17 13:54 UTC
While running a pull job over night the zrepl process was killed by kernel oom-killer while using ~8.5GiB of memory.
This looks like a memory leak.

**syslog:**
```
Feb 17 13:26:43 some-laptop kernel: oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/user.slice/user-1000.slice/user@1000.service,task=zrepl-linux-amd,pid=2032984,uid=0
Feb 17 13:26:43 some-laptop kernel: Out of memory: Killed process 2032984 (zrepl-linux-amd) total-vm:11150504kB, anon-rss:9176128kB, file-rss:0kB, shmem-rss:0kB, UID:0 pgtables:18388kB oom_score_adj:0
Feb 17 13:26:43 some-laptop kernel: oom_reaper: reaped process 2032984 (zrepl-linux-amd), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
```

**zrepl daemon log:**
```
2021-02-17T05:00:57+01:00 [ERRO][pull_job][repl][Uv38$JVXJ$p8VI$p8VI.DxEM.7+yM]: send request failed filesystem="rpool/pve/rpool/data/subvol-101-disk-0" err="dial_timeout of 10s exceeded"                                                              
2021-02-17T05:01:07+01:00 [ERRO][pull_job][repl][Uv38$JVXJ$EphZ$EphZ.D35T.rgMR]: send request failed err="dial_timeout of 10s exceeded" filesystem="rpool/pve/rpool/data/subvol-101-disk-3"                                                              
2021-02-17T05:01:28+01:00 [ERRO][pull_job][repl][Uv38$JVXJ$ojLj$ojLj.LArL.0C54]: send request failed filesystem="rpool/pve/rpool/data/vm-304-disk-0" err="dial_timeout of 10s exceeded"                                                                  
2021-02-17T12:15:49+01:00 [ERRO][pull_job][repl][Uv38$JVXJ$JVXJ.7i76.Wb+R.57Ol]: most recent error in this attempt err="dial_timeout of 10s exceeded" attempt_number="0"                                                                                 
2021-02-17T12:15:49+01:00 [ERRO][pull_job][repl][Uv38$JVXJ$JVXJ.7i76.Wb+R.57Ol]: most recent error cannot be solved by reconnecting, aborting run attempt_number="0"                                                                                     
2021-02-17T12:34:24+01:00 [ERRO][_control][job][Uv38$Uv38]: control handler io error err="write unix /var/run/zrepl/control->@: i/o timeout"                                                                                                                
2021-02-17T12:34:57+01:00 [ERRO][_control][job][Uv38$Uv38]: control handler io error err="write unix /var/run/zrepl/control->@: i/o timeout"                                                                                                                
2021-02-17T12:36:57+01:00 [ERRO][_control][job][Uv38$Uv38]: control handler io error err="write unix /var/run/zrepl/control->@: i/o timeout"                                                                                                                
2021-02-17T12:40:50+01:00 [ERRO][_control][job][Uv38$Uv38]: control handler io error err="write unix /var/run/zrepl/control->@: i/o timeout"                                                                                                                
./daemon.sh: line 26: 2032983 Killed                  sudo artifacts/zrepl-linux-amd64 daemon --config zrepl.yml
```
*I think the log messages are maybe not related to the error.*

I had the same symptoms a few weeks ago on a Raspberry Pi 4B with 2GB RAM, but I thought this would be a problem of the small system and I did not open a issue. But now I have the same symptoms again on my laptop with plenty of RAM.

**Used Version:**
Dist: Archlinux
zfs: 2.0.3 (dkms)
zrepl: branch `problame/develop` + `status-v2` (see [here](https://github.com/MAFLO321/zrepl/commit/409b56e2e0df7c9e8ac31456409e8cf97bc21ba8))

I'm currently running the job again (with loglevel debug), maybe i can get some more details. \
@problame: Can you give me some tool/commands with which I can give you more details, please?

**Comment by problame** [comment] 2021-02-17 20:39
Thanks for this bug report.

>  @problame: Can you give me some tool/commands with which I can give you more details, please?

There are [Go heap profiles](https://golang.org/doc/diagnostics) via pprof and [zrepl provides a pprof endpoint](https://github.com/zrepl/zrepl/wiki/Debugging) but AFAIK they don't work on coredumps.
So: does the RAM use ramp up slowly or is it a sudden jump with immediate OOM kill?

zrepl's [Prometheus endpoint](https://zrepl.github.io/configuration/monitoring.html?highlight=grafana) exposes Go runtime metrics, including memory usage. If you use the zrepl Grafana dashboard it should be easy to determine whether it's a ramp-up or not.

**Comment by MAFLO321** [comment] 2021-04-21 15:03
Some more logs: https://gist.github.com/MAFLO321/267657211572ed796451bee3cff7c08c
- journalctl_2021-04-21_081441.log: go runtime found oom `fatal error: runtime: out of memory`
- journalctl_2021-04-21_125203.log: kernel found oom `zrepl invoked oom-killer`
- zrepl_pprof_\<date\>\_<time\>\_\<mem procent of host\>: `curl -s http://localhost:12345/debug/pprof/goroutine?debug=1 > "zrepl_pprof_$(date +'%F_%H%M%S')"_xx`
  - daemon was started some 1.5 hours before first file (2021-04-21 12:52:06)
  - daemon was killed because of oom some ~5 minutes after last file (2021-04-21 16:40:09)

__Used Version:__
Host: odroid n2 (4 GB RAM)
Dist: Ubuntu 20.04
zfs: 2.0.3 (dkms)
zrepl: 0.4.0 ([zrepl_0.4.0_arm64.deb](https://github.com/zrepl/zrepl/releases/download/v0.4.0/zrepl_0.4.0_arm64.deb))

**Comment by 3nprob** [comment] 2021-06-23 06:15
Getting this consistently as well.
Receiver end on a single encrypted pull job eventually gets killed.

I'll see if I can gather more useful info. In either case, by looking at is as it's running, it seems memory usage of zrepl is building up incrementally with each STEP.

**Comment by MAFLO321** [comment] 2021-06-23 11:35
> I'm not sure exactly what's going on here and it's years since I worked with Go slices, but this line stands out a bit to me in this context - will this not create a new references allocation with each call?
> https://github.com/zrepl/zrepl/blob/3b5a1a8b9a14c167d1af3ab7af115d5f9ffe9c2f/rpc/dataconn/base2bufpool/base2bufpool.go#L32

I'm not really into go but what I found on the go wiki to this: https://github.com/golang/go/wiki/SliceTricks#pop

---

If this help's, I could provide coredumps generated by `gcore {PID}` of a zrepl instance in multiple memory usage states (8%, 14%, ..., 57% of 4 GB host memory) (as you might guess they are quit big (1.4 GB - 2.9 GB). Therefore, please ask, and I will send you a private link via mail)

**Comment by problame** [comment] 2021-06-23 12:28
> . Adding virtual memory it goes for longer but eventually the same thing.

@3nprob what do you mean by 'adding virtual memory'? Are you using resource limits?

**Comment by 3nprob** [comment] 2021-06-24 02:11
@problame No no, just added and enabled a 7GB swap file (:

**Comment by 3nprob** [comment] 2021-06-24 17:00
I was doing this in order to see if it gets killed at a particular step:

```
watch -n1 'ps -Af | grep "zfs " | grep -v "grep " >> zfsprocs.log'
```

It does seem to be coinciding with `zfs destroy` on the recipient. Maybe the situation could be alleviated by destroying fewer snapshots (or even a single one) at a time? I guess the buik destroy can create additional pressure.

**Comment by problame** [comment] 2021-06-28 10:57
@3nprob thanks for debugging this!
Yeah, I can imagine bulk destroys making trouble.

The code that checks for support for the comma syntax that we use for bulk destroys is here:

https://github.com/zrepl/zrepl/blob/10a14a8c5016e8f7d3f145fdfd8ee76af274ede8/zfs/versions_destroy.go#L224-L239

If you start the daemon with env var `ZREPL_EXPERIMENTAL_ZFS_COMMA_SYNTAX_SUPPORTED=false` zrepl should never be using the bulk destroys.

Out of curiosity: how many snapshots are we talking about? (scrape it from your log, something like., `cat ... | grep 'zfs destroy' | xargs -n 1 bash -c 'echo $0 | sed "s/,/\n/g" | wc -l'`)

**Comment by 3nprob** [comment] 2021-07-08 06:30
Sorry for not following up on this - I managed to eat through the backlog of snapshots through a series of restarts over several days and don't have logs retained that far back.

But once ZFS 2.1 with https://github.com/openzfs/zfs/pull/12266 lands in debian repos I should hopefully be able to replicate it again with the other datasets that are currently blocked from syncing.

In either case, I'm pretty sure the bulk destroys were the trigger and not the main issue here - even now, memory usage builds up slowly over time and remains high even as no current activity is going on. The zrepl daemon gets OoM-killed once every day or two.

**Comment by problame** [comment] 2021-07-08 11:52
@3nprob in the meantime, it would be really useful to set up Prometheus + Grafana. We have graphs for metrics from the Go runtime that indicate number of goroutines, memory usage, etc. https://zrepl.github.io/configuration/monitoring.html?highlight=grafana

**Comment by 3nprob** [comment] 2022-03-22 09:14
So as syncing has resumed, so has this issue (though now it's a matter of hours, not days). Hopefully I can get some more helpful profiling data to help pin this down.

**Comment by problame** [comment] 2022-10-23 15:39
@3nprob  I guess we can call this fixed by your PR https://github.com/zrepl/zrepl/pull/604 ?

**Comment by mateuszkwiatkowski** [comment] 2024-09-24 11:41
I can confirm that setting `ZREPL_DESTROY_MAX_BATCH_SIZE` fixed the OOM problem for me.
I'm not sure what is the root cause. I have another backup server with much more snapshots, much less memory (16GB vs 4GB!) and never experienced OOM there. 

Here are details about problematic server:
```
# sysctl hw.physmem
hw.physmem: 17024753664

# zrepl version
client: zrepl version=v0.6.1 go=go1.21.12 GOOS=freebsd GOARCH=amd64 Compiler=gc
server: zrepl version=v0.6.1 go=go1.21.12 GOOS=freebsd GOARCH=amd64 Compiler=gc

# uname -a
FreeBSD backup-1 13.2-RELEASE-p2 FreeBSD 13.2-RELEASE-p2 GENERIC amd64

# zfs list -t snapshot | wc -l
     280

# zpool version
zfs-2.1.9-FreeBSD_g92e0d9d18
zfs-kmod-2.1.9-FreeBSD_g92e0d9d18
```

And server that never had OOM issue (it was recently upgrade do 14.1, previously was running on 13.2 and also was working without any issues):

```
# sysctl hw.physmem
hw.physmem: 4250365952

# zrepl version
client: zrepl version=v0.6.1 go=go1.21.12 GOOS=freebsd GOARCH=amd64 Compiler=gc
server: zrepl version=v0.6.1 go=go1.21.12 GOOS=freebsd GOARCH=amd64 Compiler=gc

# uname -a
FreeBSD backup-2 14.1-RELEASE-p4 FreeBSD 14.1-RELEASE-p4 GENERIC amd64

# zfs list -t snapshot | wc -l
    1067
    
# zpool version
zfs-2.2.4-FreeBSD_g256659204
zfs-kmod-2.2.4-FreeBSD_g256659204
```

**Comment by problame** [comment] 2024-10-27 22:25
Let's create a new issue to track (potentially new) platform problems with FreeBSD 14.1.

**Closed by problame** 2024-10-27 22:25 UTC
Labels: bug, awaiting_feedback
