### ISSUE TITLE
Snap dont prune in receive

### ISSUE THREAD

**Issue by ivanrzk** [zrepl/zrepl#389] opened 2020-09-24 14:41 UTC
Hi,
I have one hostA int mode push, snap and replicating to another hostB
We have in hostA snap generated manually with openstack with regex @snapshot-*
This is the conf in hostA
```
 snapshotting:
    type: periodic
    prefix: zrepl_
    interval: 10m
  pruning:
    keep_sender:
    - type: not_replicated
    - type: regex
      regex: "^(snapshot|autosnap|).*"
    - type: last_n
      count: 24
    keep_receiver:
    - type: grid
      grid: 1x1h(keep=all) | 24x1h | 30x1d | 6x30d
      regex: "^zrepl_"
```
In hostA is Ok to keep manually snap but in the hostB dont and is keeping on the receive side.
Ex on hostB:
```
volume-6ab0815b-516c-48de-990a-0ba027ad26f5@zrepl_20200924_140738_000                     
volume-6ab0815b-516c-48de-990a-0ba027ad26f5@zrepl_20200924_141738_000                 
volume-6ab0815b-516c-48de-990a-0ba027ad26f5@snapshot-95988de2-686c-4fa0-b4ca-bc44aa15bd0e
volume-6ab0815b-516c-48de-990a-0ba027ad26f5@snapshot-e87657f7-a3ba-4edc-8641-ae7c996cf311
volume-6ab0815b-516c-48de-990a-0ba027ad26f5@snapshot-eb04b65c-b141-43ba-82c6-e55a9fc0bfa4
volume-6ab0815b-516c-48de-990a-0ba027ad26f5@snapshot-9d3233ea-04aa-4f11-9a9a-d74d3c7697ef
volume-6ab0815b-516c-48de-990a-0ba027ad26f5@zrepl_20200924_142740_000
```
The problem is dont prune the snapshot.* regex in receive side.
What am I doing wrong?
Thx.
Best regards.

**Comment by problame** [comment] 2020-09-25 07:00
I'm not sure I understand what you're trying to achieve.
Do you want to only replicate snapshots creates by zrepl?

**Comment by ivanrzk** [comment] 2020-09-25 12:55
Hi, sorry for my english.
Yes, i want to keep only zrepl snap on the receive side.

**Comment by problame** [comment] 2020-09-25 16:09
Then this is a duplicate of #248 , right?

**Comment by ivanrzk** [comment] 2020-09-25 17:36
thx for the reply
Probably filter sender snap might work, but my question is:
In the receive side only prune snap created for zrep? if i understand correctly.

**Comment by problame** [comment] 2020-09-25 17:38
The configuration you posted above _keeps_ on the receiver only snapshots that match `^zrepl_`.
All other snapshots on the receiving-side filesystems are destroyed.

**Comment by ivanrzk** [comment] 2020-09-25 17:54
Exactly, i understand this is was expect. But is not work, does not prune the snaps with regex snapshot.* replicated with zrepl.
This is an example of receiving-side filesystem:
```
Storage01/zrepl/sink/prod/Storage01/volume-a59b979c-25af-4237-bbc8-e35d7d93d926@zrepl_20200925_112738_000
Storage01/zrepl/sink/prod/Storage01/volume-a59b979c-25af-4237-bbc8-e35d7d93d926@zrepl_20200925_122738_000
Storage01/zrepl/sink/prod/Storage01/volume-a59b979c-25af-4237-bbc8-e35d7d93d926@zrepl_20200925_132738_000
Storage01/zrepl/sink/prod/Storage01/volume-a59b979c-25af-4237-bbc8-e35d7d93d926@zrepl_20200925_142738_000
Storage01/zrepl/sink/prod/Storage01/volume-a59b979c-25af-4237-bbc8-e35d7d93d926@snapshot-7f559f43-1409-4feb-b1d8-9023964a07d3
Storage01/zrepl/sink/prod/Storage01/volume-a59b979c-25af-4237-bbc8-e35d7d93d926@zrepl_20200925_152738_000

**Comment by problame** [comment] 2020-09-25 20:18
Oh, this is a duplicate of https://github.com/zrepl/zrepl/issues/292 then. 

You can build zrepl master from source or use the zrepl CI artifacts to see if it fixed your problem.

**Comment by problame** [comment] 2020-09-25 20:20
Artifacts of current master HEAD: https://minio.cschwarz.com/minio/zrepl-ci-artifacts/2ba6aabd4a6b2503ff92a849cd874ffa68a9956e-pipeline-975/release-upload/

**Comment by ivanrzk** [comment] 2020-09-28 15:52
Yes.
Re-build with version:
````
 zrepl version
client: zrepl version=v0.3.0-36-g2ba6aab go=go1.15.2 GOOS=linux GOARCH=amd64 Compiler=gc
server: zrepl version=v0.3.0-36-g2ba6aab go=go1.15.2 GOOS=linux GOARCH=amd64 Compiler=gc
````
And work OK.
Thx for help.

**Closed** 2020-10-01 09:50 UTC
Labels: question, usability
