### ISSUE TITLE
Feature Request: Send mail on job success/failure

### ISSUE THREAD

**Issue by MarcusWichelmann** [zrepl/zrepl#395] opened 2020-10-12 11:29 UTC
I'm using zrepl to do daily backups of some servers. But in case the backup job on one of the servers fails, I would probably not notice that until the next time I manually log onto the server and check the zrepl status.

It would be very helpful, if I could enable mail notifications in zrepl, so it uses the local postfix installation to send me a mail in case something goes wrong. Maybe one could even control, whether a mail should be sent after successful job executions, too. Just for feeling safe. :smile: 
Same goes for snapshotting.

As an alternative to using the local postfix installation (like zfs-zed does), zrepl could also use some SMTP library so the server and authenticationo can be configured directly within the zrepl.yml for easier setup.

How do you think about adding this feature? Or is there already an alternative solution to this?

**Comment by problame** [comment] 2020-10-12 12:48
We just got another feature request for generic pre- and post-job invocation hooks #394 . This would allow you to run a shell script pre and post job invocation. I would imagine that you could use such a hook to accomplish your goal.
If so, please comment there on what metadata you would want to have available in the hook and in what format.

**Comment by problame** [comment] 2020-10-13 10:25
Closing as a duplicate of #394

**Closed by problame** 2020-10-13 10:25 UTC
Labels: analysis, feature
