### ISSUE TITLE
Error: zfs: replication cursor: can only be advanced, not set back

### ISSUE THREAD

**Issue by Thoro** [zrepl/zrepl#250] opened 2019-11-29 08:54 UTC
Gives no hint on why it happens, and on which dataset it happened, therefore is impossible to figure out without turning on debug level logs.

**Comment by problame** [comment] 2019-11-29 09:44
Where did you read that error message? In a log message or `zrepl status`?

**Comment by Thoro** [comment] 2019-11-29 10:20
zrepl status

**Comment by problame** [comment] 2019-11-29 10:30
Interesting.

In `zrepl status`, replication cursor errors should always be displayed on the same line as the filesystem (filesystem left, some whitespace, then an error that occurred in a replication step).

Did the debug log contain the filesystem name? And do you, by any chance, recall the exact wording of the log line?

**Comment by Thoro** [comment] 2019-11-29 10:53
True, zrepl status shows next to filesystem message, but I also ran into the issue #245 

So it's only about the log output.

In log it looks like this:

2019-11-29T10:44:49Z [ERRO][storage_to_backups][repl]: error advancing replication cursor invocation="3" err="zfs: replication cursor: can only be advanced, not set back"

I adapted the error to read like this:

2019-11-29T10:44:49Z [ERRO][storage_to_backups][repl]: error advancing replication cursor invocation="3" err="zfs: replication cursor: can only be advanced, not set back: storage/cluster/pvc-6e9b01f1-8e7c-11e9-b1c3-9c8e990f7e46#zrepl_replication_cursor" 

So I can figure out what error it was.

**Comment by Thoro** [comment] 2019-11-29 10:56
The next question is, how this error even happened, since the target does not contain the referenced snapshot from the cursor.

**Comment by problame** [comment] 2019-12-02 12:22
Depending on the pruning rules on the receiving side, the pruner on the receiving side might have destroyed an already replicated snapshot. I always have `last_n` as part of the receive-side keep rules to ensure that the last replicated snapshot is always present on the receiver.
`grid:` with first interval on `keep=all` should do the trick as well.

Maybe related: I'm working on an updated design of the replication code as part of the resumable send & recv work: https://github.com/zrepl/zrepl/blob/problame/resumable-and-encrypted-send-recv/replication/design.md

**Comment by problame** [comment] 2020-01-30 19:03
@Thoro the aforementioned replication design rework is now open as #259 and needs testers!

**Comment by problame** [comment] 2020-02-17 21:23
@Thoro #259 is now merged into master and will be released shortly. Any testing is highly appreciated!

**Comment by TitusLabienus** [comment] 2020-04-08 03:22
I am encountering this issue too. When I try to replicate filesystems via the manual mode, I encounter this issue after only a few seconds and can hardly replicate 1-2 snapshots on average. Thus, this bug blocks me from using zrepl.

**Comment by TitusLabienus** [comment] 2020-04-08 03:24
@problame Can you reproduce this issue as consistently as I can (i.e. making manual replication practically impossible)? If not, I can provide you with a minimalistic .yml file or similar.

**Comment by problame** [comment] 2020-04-08 07:11
Please try the latest master, or, even better, #303  - to get pre-built binaries, click on the commit status (the green checkmark) and then click on the artifact download button. 
Then report back, including the configs of both sides, OS version, ZFS version, and `zrepl version` output of both sides.

**Comment by problame** [comment] 2020-06-14 13:58
Closing this due to inactivity.

**Closed by problame** 2020-06-14 13:58 UTC
Labels: awaiting_feedback, bug, usability
