### ISSUE TITLE
Zrepl is sending all snapshots not only zrepl_ prefix

### ISSUE THREAD

**Issue by chomiczon** [zrepl/zrepl#491] opened 2021-06-09 06:08 UTC
Hi.

Zrepl is sending all snapshots not only zrepl_ prefix. It's causings replication conflicts and sending errors. When I create manual snapshot from proxmox and zrepl sending zrepl_ snap + my manual snap and manual snap exists on sink then zrepl is reporting conflict error.

**Comment by InsanePrawn** [comment] 2021-06-09 13:34
Hello there, this is a duplicate of #403, a feature to address this is being worked on in #459.
If you have something new to add to the discussion, please participate in those threads.
Thanks!

**Closed by InsanePrawn** 2021-06-09 13:34 UTC
