### ISSUE TITLE
Gracefully handle unexpected broken connection

### ISSUE THREAD

**Issue by MoritzFago** [zrepl/zrepl#81] opened 2018-06-22 01:04 UTC
After the transfer connection between pull and source is destroyed (for example because your ISP kills the connection every 24h for historic reasons) zrepl doesn't recover, but needs a manual restart on both ends.

**Comment by shivno** [comment] 2018-06-25 11:21
this is a dupe of my bug i think

**Closed** 2018-10-17 08:06 UTC
Labels: 0.1, bug
