### ISSUE TITLE
Value out of range with zfs send dry

### ISSUE THREAD

**Issue by Debilski** [zrepl/zrepl#511] opened 2021-09-03 16:11 UTC
I’m getting planning-errors with a bunch of file systems with error messages such as:

    dry run send request failed err="zfs send dry failed: could not parse zfs send -n output:
      line \"incremental\\tPOOL/fs@zrepl_20210811_080209_000\\POOL/fs@zrepl_20210811_090141_000\\t18446744073651306528\":
      cannot not parse size: strconv.ParseInt: parsing \"18446744073651306528\": value out of range"
    error computing size estimate filesystem="POOL/fs" err="zfs send dry failed: could not parse zfs send -n output:
      line \"incremental\\tPOOL/fs@zrepl_20210811_080209_000\\tPOOL/fs@zrepl_20210811_090141_000\\t18446744073651306528\":
      cannot not parse size: strconv.ParseInt: parsing \"18446744073651306528\": value out of range" step="POOL/fs(@zrepl_20210811_080209_000 => @zrepl_20210811_090141_000)"

The number seems unreasonably large. Is this an error in my zpool (and if so, how could I investigate it) or something in zrepl?

**Comment by problame** [comment] 2021-09-04 05:42
Duplicate of #463.

Could you test https://github.com/zrepl/zrepl/commits/dry-send-rework ? See the commit message of the topmost commit in that series, but use all commits: https://github.com/zrepl/zrepl/commit/302c8dadf9cfb4bf0134696dc90fc76f28e35713

**Closed** 2021-09-04 05:42 UTC
Labels: duplicate

**Comment by Debilski** [comment] 2021-09-04 09:02
Whoops, sorry, kind of missed the obvious issue there. The fix is currently doing the job (though it hasn’t finished yet).
