### ISSUE TITLE
[RFE] Create all the snapshots at the same time

### ISSUE THREAD

**Issue by lapo-luchini** [zrepl/zrepl#251] opened 2019-12-02 13:49 UTC
I've noticed that even for `fs<` rules, the snapshots are created one by one, in sequence:
![image](https://user-images.githubusercontent.com/420454/69964150-14284700-1512-11ea-9dc1-44c1b3dd1f8c.png)
It would be nice to use `zfs snapshot -r` in those rules, so that less time is taken and all the snapshots are done in the same instant.
This would also improve consistency among different filesystems.

Actually, I see in the `man` that it's also possible to snapshot multiple filesystems (with `zfs snapshot [-r] fsA, fsB, fsC…`) but it's not possible to mix recursive and non-recursive ones, so probably the only way to snapshot them all at the very same instant is listing them one by one, non recursive (unless the command has a length limitation).

**Comment by lapo-luchini** [comment] 2019-12-02 13:50
Uh, I noticed that only a split second after submit… this might be related to #62?

**Comment by problame** [comment] 2019-12-04 09:04
Yes, this is a duplicate of #62 
Except for the interaction with the hooks feature, this might be a good issue to get started!

**Closed by problame** 2019-12-04 09:04 UTC
