### ISSUE TITLE
Ubuntu 16.04: replication cursor does not work due to bug in zfs get bookmarks

### ISSUE THREAD

**Issue by meilihao** [zrepl/zrepl#230] opened 2019-10-14 07:36 UTC
I am using `push + sink`. But pruning does't work.

env:
```
zrepl: 0.2.0
ZFS: Loaded module v0.6.5.6-0ubuntu16, ZFS pool version 5000, ZFS filesystem version 5
```

push config:
```yaml
jobs:
- type: push
  name: prod
  filesystems: {
    "storage<":true,
    "storage/tmp":false
  }
  connect:
    type: tcp
    address: "192.168.0.42:8888"
  snapshotting:
    type: periodic
    prefix: zrepl_
    interval: 2m
  pruning:
    keep_sender:
      - type: not_replicated
      - type: last_n
        count: 6
    keep_receiver:
      - type: grid
        grid: 10x1m(keep=all) | 30x1m | 1x1h | 1x1d
        regex: "^zrepl_"
```

sink config:
```yaml
jobs:
- type: sink
  name: sink
  serve:
     type: tcp
     listen: ":8888"
     clients: {
         "192.168.0.41": "from_41"
     }
  root_fs: "mypool/backup"
```

zpool:
```sh
# zpool get feature@bookmarks storage
NAME     PROPERTY           VALUE              SOURCE
storage  feature@bookmarks  active             local
```

log:
```text
2019-10-14T15:24:27+08:00 [INFO][prod]: start pruning sender invocation="28"
2019-10-14T15:24:27+08:00 [DEBG][prod][pruning]: plan filesystem fs="storage" invocation="28" prune_side="sender"
2019-10-14T15:24:27+08:00 [ERRO][prod][pruning]: : plan error, skipping filesystem invocation="28" prune_side="sender" fs="storage" orig_err_type="*errors.fundamental" err="replication cursor bookmark does not exist (one successful replication is required before pruning works)"
2019-10-14T15:24:27+08:00 [DEBG][prod][pruning]: plan filesystem invocation="28" prune_side="sender" fs="storage/a"
2019-10-14T15:24:27+08:00 [ERRO][prod][pruning]: : plan error, skipping filesystem orig_err_type="*errors.fundamental" invocation="28" prune_side="sender" err="replication cursor bookmark does not exist (one successful replication is required before pruning works)" fs="storage/a"
2019-10-14T15:24:27+08:00 [DEBG][prod][pruning]: plan filesystem prune_side="sender" fs="storage/a/c" invocation="28"
2019-10-14T15:24:27+08:00 [ERRO][prod][pruning]: : plan error, skipping filesystem invocation="28" err="replication cursor bookmark does not exist (one successful replication is required before pruning works)" prune_side="sender" fs="storage/a/c" orig_err_type="*errors.fundamental"
2019-10-14T15:24:27+08:00 [DEBG][prod][pruning]: plan filesystem prune_side="sender" fs="storage/b" invocation="28"
2019-10-14T15:24:27+08:00 [ERRO][prod][pruning]: : plan error, skipping filesystem orig_err_type="*errors.fundamental" err="replication cursor bookmark does not exist (one successful replication is required before pruning works)" prune_side="sender" fs="storage/b" invocation="28"
2019-10-14T15:24:27+08:00 [DEBG][prod][pruning]: destroying snapshots prune_side="sender" fs="storage" invocation="28"
2019-10-14T15:24:27+08:00 [DEBG][prod][pruning]: destroying snapshots invocation="28" prune_side="sender" fs="storage/a"
2019-10-14T15:24:27+08:00 [DEBG][prod][pruning]: destroying snapshots fs="storage/a/c" invocation="28" prune_side="sender"
2019-10-14T15:24:27+08:00 [DEBG][prod][pruning]: destroying snapshots prune_side="sender" fs="storage/b" invocation="28"
2019-10-14T15:24:27+08:00 [INFO][prod]: finished pruning sender invocation="28"
2019-10-14T15:24:27+08:00 [INFO][prod]: start pruning receiver invocation="28"
2019-10-14T15:24:27+08:00 [DEBG][prod][pruning]: plan filesystem invocation="28" prune_side="receiver" fs="storage"
2019-10-14T15:24:27+08:00 [ERRO][prod][pruning]: : plan error, skipping filesystem prune_side="receiver" fs="storage" orig_err_type="*errors.fundamental" err="replication cursor bookmark does not exist (one successful replication is required before pruning works)" invocation="28"
2019-10-14T15:24:27+08:00 [DEBG][prod][pruning]: plan filesystem prune_side="receiver" invocation="28" fs="storage/a"
2019-10-14T15:24:27+08:00 [ERRO][prod][pruning]: : plan error, skipping filesystem invocation="28" fs="storage/a" prune_side="receiver" orig_err_type="*errors.fundamental" err="replication cursor bookmark does not exist (one successful replication is required before pruning works)"
2019-10-14T15:24:27+08:00 [DEBG][prod][pruning]: plan filesystem prune_side="receiver" fs="storage/a/c" invocation="28"
2019-10-14T15:24:27+08:00 [ERRO][prod][pruning]: : plan error, skipping filesystem prune_side="receiver" fs="storage/a/c" orig_err_type="*errors.fundamental" invocation="28" err="replication cursor bookmark does not exist (one successful replication is required before pruning works)"
2019-10-14T15:24:27+08:00 [DEBG][prod][pruning]: plan filesystem invocation="28" prune_side="receiver" fs="storage/b"
2019-10-14T15:24:27+08:00 [ERRO][prod][pruning]: : plan error, skipping filesystem invocation="28" prune_side="receiver" fs="storage/b" orig_err_type="*errors.fundamental" err="replication cursor bookmark does not exist (one successful replication is required before pruning works)"
2019-10-14T15:24:27+08:00 [DEBG][prod][pruning]: destroying snapshots prune_side="receiver" fs="storage" invocation="28"
2019-10-14T15:24:27+08:00 [DEBG][prod][pruning]: destroying snapshots invocation="28" prune_side="receiver" fs="storage/a"
2019-10-14T15:24:27+08:00 [DEBG][prod][pruning]: destroying snapshots invocation="28" prune_side="receiver" fs="storage/a/c"
2019-10-14T15:24:27+08:00 [DEBG][prod][pruning]: destroying snapshots prune_side="receiver" fs="storage/b" invocation="28"
2019-10-14T15:24:27+08:00 [INFO][prod]: finished pruning receiver invocation="28"
2019-10-14T15:24:27+08:00 [INFO][prod]: wait for wakeups
```

**Comment by problame** [comment] 2019-10-14 11:19
As indicated in the error message:

```
replication cursor bookmark does not exist (one successful replication is required before pruning works)
```

Does the problem persist after the first successful replication?

**Comment by meilihao** [comment] 2019-10-14 11:39
replication is ok, 


example :  `storage/b`

push side:
```log
# zfs list -t all
storage/b                                19K  3.83G    19K  /storage/b
storage/b@zrepl_20191014_063026_000        0      -    19K  -
storage/b@zrepl_20191014_063226_000        0      -    19K  -
storage/b@zrepl_20191014_063426_000        0      -    19K  -
storage/b@zrepl_20191014_063626_000        0      -    19K  -
storage/b@zrepl_20191014_063826_000        0      -    19K  -
storage/b@zrepl_20191014_064026_000        0      -    19K  -
storage/b@zrepl_20191014_064226_000        0      -    19K  -
storage/b@zrepl_20191014_064426_000        0      -    19K  -
storage/b@zrepl_20191014_064626_000        0      -    19K  -
storage/b@zrepl_20191014_064826_000        0      -    19K  -
storage/b@zrepl_20191014_065026_000        0      -    19K  -
storage/b@zrepl_20191014_065226_000        0      -    19K  -
storage/b@zrepl_20191014_065426_000        0      -    19K  -
storage/b@zrepl_20191014_065626_000        0      -    19K  -
storage/b@zrepl_20191014_065826_000        0      -    19K  -
storage/b@zrepl_20191014_070026_000        0      -    19K  -
storage/b@zrepl_20191014_070226_000        0      -    19K  -
storage/b@zrepl_20191014_070426_000        0      -    19K  -
storage/b@zrepl_20191014_070626_000        0      -    19K  -
storage/b@zrepl_20191014_070826_000        0      -    19K  -
storage/b@zrepl_20191014_071026_000        0      -    19K  -
storage/b@zrepl_20191014_071226_000        0      -    19K  -
storage/b@zrepl_20191014_071426_000        0      -    19K  -
storage/b@zrepl_20191014_071627_000        0      -    19K  -
storage/b@zrepl_20191014_071826_000        0      -    19K  -
storage/b@zrepl_20191014_072027_000        0      -    19K  -
storage/b@zrepl_20191014_072227_000        0      -    19K  -
storage/b@zrepl_20191014_072426_000        0      -    19K  -
storage/b@zrepl_20191014_072626_000        0      -    19K  -
storage/b@zrepl_20191014_072827_000        0      -    19K  -
storage/b@zrepl_20191014_073026_000        0      -    19K  -
storage/b@zrepl_20191014_073226_000        0      -    19K  -
storage/b@zrepl_20191014_073426_000        0      -    19K  -
storage/b@zrepl_20191014_073627_000        0      -    19K  -
storage/b@zrepl_20191014_073827_000        0      -    19K  -
storage/b@zrepl_20191014_074026_000        0      -    19K  -
storage/b@zrepl_20191014_074227_000        0      -    19K  -
storage/b@zrepl_20191014_074426_000        0      -    19K  -
storage/b@zrepl_20191014_074626_000        0      -    19K  -
storage/b@zrepl_20191014_074827_000        0      -    19K  -
storage/b@zrepl_20191014_075027_000        0      -    19K  -
storage/b@zrepl_20191014_075227_000        0      -    19K  -
storage/b@zrepl_20191014_075427_000        0      -    19K  -
storage/b@zrepl_20191014_075626_000        0      -    19K  -
storage/b@zrepl_20191014_075827_000        0      -    19K  -
storage/b@zrepl_20191014_080027_000        0      -    19K  -
storage/b@zrepl_20191014_080227_000        0      -    19K  -
storage/b@zrepl_20191014_080427_000        0      -    19K  -
storage/b@zrepl_20191014_080626_000        0      -    19K  -
storage/b@zrepl_20191014_080827_000        0      -    19K  -
storage/b@zrepl_20191014_081026_000        0      -    19K  -
storage/b@zrepl_20191014_081227_000        0      -    19K  -
storage/b@zrepl_20191014_081427_000        0      -    19K  -
storage/b@zrepl_20191014_081626_000        0      -    19K  -
storage/b@zrepl_20191014_081827_000        0      -    19K  -
storage/b@zrepl_20191014_082027_000        0      -    19K  -
storage/b@zrepl_20191014_082227_000        0      -    19K  -
storage/b@zrepl_20191014_082427_000        0      -    19K  -
storage/b@zrepl_20191014_082627_000        0      -    19K  -
storage/b@zrepl_20191014_082827_000        0      -    19K  -
storage/b@zrepl_20191014_083027_000        0      -    19K  -
storage/b@zrepl_20191014_083227_000        0      -    19K  -
storage/b@zrepl_20191014_083427_000        0      -    19K  -
storage/b@zrepl_20191014_083627_000        0      -    19K  -
storage/b@zrepl_20191014_083827_000        0      -    19K  -
storage/b@zrepl_20191014_084027_000        0      -    19K  -
storage/b@zrepl_20191014_084227_000        0      -    19K  -
storage/b@zrepl_20191014_084427_000        0      -    19K  -
storage/b@zrepl_20191014_084627_000        0      -    19K  -
storage/b@zrepl_20191014_084827_000        0      -    19K  -
storage/b@zrepl_20191014_085027_000        0      -    19K  -
storage/b@zrepl_20191014_085227_000        0      -    19K  -
storage/b@zrepl_20191014_085427_000        0      -    19K  -
storage/b@zrepl_20191014_085627_000        0      -    19K  -
storage/b@zrepl_20191014_085827_000        0      -    19K  -
storage/b@zrepl_20191014_090027_000        0      -    19K  -
storage/b@zrepl_20191014_090227_000        0      -    19K  -
storage/b@zrepl_20191014_090427_000        0      -    19K  -
storage/b@zrepl_20191014_090627_000        0      -    19K  -
storage/b@zrepl_20191014_090827_000        0      -    19K  -
storage/b@zrepl_20191014_091026_000        0      -    19K  -
storage/b@zrepl_20191014_091227_000        0      -    19K  -
storage/b@zrepl_20191014_091427_000        0      -    19K  -
storage/b@zrepl_20191014_091627_000        0      -    19K  -
storage/b@zrepl_20191014_091827_000        0      -    19K  -
storage/b@zrepl_20191014_092027_000        0      -    19K  -
storage/b@zrepl_20191014_092227_000        0      -    19K  -
storage/b@zrepl_20191014_092427_000        0      -    19K  -
storage/b@zrepl_20191014_092627_000        0      -    19K  -
storage/b@zrepl_20191014_092827_000        0      -    19K  -
storage/b@zrepl_20191014_093027_000        0      -    19K  -
storage/b@zrepl_20191014_093227_000        0      -    19K  -
storage/b@zrepl_20191014_093427_000        0      -    19K  -
storage/b@zrepl_20191014_093627_000        0      -    19K  -
storage/b@zrepl_20191014_093827_000        0      -    19K  -
storage/b@zrepl_20191014_094027_000        0      -    19K  -
storage/b@zrepl_20191014_094227_000        0      -    19K  -
storage/b@zrepl_20191014_094427_000        0      -    19K  -
storage/b@zrepl_20191014_094627_000        0      -    19K  -
storage/b@zrepl_20191014_094827_000        0      -    19K  -
storage/b@zrepl_20191014_095027_000        0      -    19K  -
storage/b@zrepl_20191014_095227_000        0      -    19K  -
storage/b@zrepl_20191014_095427_000        0      -    19K  -
storage/b@zrepl_20191014_095627_000        0      -    19K  -
storage/b@zrepl_20191014_095827_000        0      -    19K  -
storage/b@zrepl_20191014_100027_000        0      -    19K  -
storage/b@zrepl_20191014_100227_000        0      -    19K  -
storage/b@zrepl_20191014_100427_000        0      -    19K  -
storage/b@zrepl_20191014_100627_000        0      -    19K  -
storage/b@zrepl_20191014_100827_000        0      -    19K  -
storage/b@zrepl_20191014_101027_000        0      -    19K  -
storage/b@zrepl_20191014_101227_000        0      -    19K  -
storage/b@zrepl_20191014_101427_000        0      -    19K  -
storage/b@zrepl_20191014_101627_000        0      -    19K  -
storage/b@zrepl_20191014_101827_000        0      -    19K  -
storage/b@zrepl_20191014_102027_000        0      -    19K  -
storage/b@zrepl_20191014_102227_000        0      -    19K  -
storage/b@zrepl_20191014_102427_000        0      -    19K  -
storage/b@zrepl_20191014_102627_000        0      -    19K  -
storage/b@zrepl_20191014_102827_000        0      -    19K  -
storage/b@zrepl_20191014_103027_000        0      -    19K  -
storage/b@zrepl_20191014_103227_000        0      -    19K  -
storage/b@zrepl_20191014_103427_000        0      -    19K  -
storage/b@zrepl_20191014_103627_000        0      -    19K  -
storage/b@zrepl_20191014_103827_000        0      -    19K  -
storage/b@zrepl_20191014_104027_000        0      -    19K  -
storage/b@zrepl_20191014_104227_000        0      -    19K  -
storage/b@zrepl_20191014_104427_000        0      -    19K  -
storage/b@zrepl_20191014_104627_000        0      -    19K  -
storage/b@zrepl_20191014_104827_000        0      -    19K  -
storage/b@zrepl_20191014_105027_000        0      -    19K  -
storage/b@zrepl_20191014_105227_000        0      -    19K  -
storage/b@zrepl_20191014_105427_000        0      -    19K  -
storage/b@zrepl_20191014_105627_000        0      -    19K  -
storage/b@zrepl_20191014_105827_000        0      -    19K  -
storage/b@zrepl_20191014_110027_000        0      -    19K  -
storage/b@zrepl_20191014_110227_000        0      -    19K  -
storage/b@zrepl_20191014_110427_000        0      -    19K  -
storage/b@zrepl_20191014_110627_000        0      -    19K  -
storage/b@zrepl_20191014_110827_000        0      -    19K  -
storage/b@zrepl_20191014_111027_000        0      -    19K  -
storage/b@zrepl_20191014_111227_000        0      -    19K  -
storage/b@zrepl_20191014_111427_000        0      -    19K  -
storage/b@zrepl_20191014_111627_000        0      -    19K  -
storage/b@zrepl_20191014_112106_000        0      -    19K  -
storage/b@zrepl_20191014_112306_000        0      -    19K  -
storage/b@zrepl_20191014_112506_000        0      -    19K  -
storage/b@zrepl_20191014_112706_000        0      -    19K  -
storage/b@zrepl_20191014_112906_000        0      -    19K  -
```

sink side:
```log
# zfs list -t all
mypool/backup/from_41/storage/b                               164K  3.83G    19K  none
mypool/backup/from_41/storage/b@zrepl_20191014_063026_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_063226_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_063426_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_063626_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_063826_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_064026_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_064226_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_064426_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_064626_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_064826_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_065026_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_065226_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_065426_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_065626_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_065826_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_070026_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_070226_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_070426_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_070626_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_070826_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_071026_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_071226_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_071426_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_071627_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_071826_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_072027_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_072227_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_072426_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_072626_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_072827_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_073026_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_073226_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_073426_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_073627_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_073827_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_074026_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_074227_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_074426_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_074626_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_074827_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_075027_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_075227_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_075427_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_075626_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_075827_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_080027_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_080227_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_080427_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_080626_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_080827_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_081026_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_081227_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_081427_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_081626_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_081827_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_082027_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_082227_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_082427_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_082627_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_082827_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_083027_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_083227_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_083427_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_083627_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_083827_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_084027_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_084227_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_084427_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_084627_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_084827_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_085027_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_085227_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_085427_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_085627_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_085827_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_090027_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_090227_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_090427_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_090627_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_090827_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_091026_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_091227_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_091427_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_091627_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_091827_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_092027_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_092227_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_092427_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_092627_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_092827_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_093027_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_093227_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_093427_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_093627_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_093827_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_094027_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_094227_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_094427_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_094627_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_094827_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_095027_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_095227_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_095427_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_095627_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_095827_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_100027_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_100227_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_100427_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_100627_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_100827_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_101027_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_101227_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_101427_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_101627_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_101827_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_102027_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_102227_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_102427_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_102627_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_102827_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_103027_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_103227_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_103427_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_103627_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_103827_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_104027_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_104227_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_104427_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_104627_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_104827_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_105027_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_105227_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_105427_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_105627_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_105827_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_110027_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_110227_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_110427_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_110627_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_110827_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_111027_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_111227_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_111427_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_111627_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_112106_000       1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_112306_000        1K      -    19K  -
mypool/backup/from_41/storage/b@zrepl_20191014_112506_000        0      -    19K  -
```

**Comment by problame** [comment] 2019-10-14 14:54
Sry for mis-triaging this:
The real problem is that the (very old) 16.04 ZFS version doesn't support getting properties of a bookmark, which we rely on to get the replication cursor `guid` and `createtxg`.

Steps to reproduce:
```bash
# create a pool
root@ubuntu16: truncate -s 1G /pool.img
root@ubuntu16: zpool create pool /pool.img
root@ubuntu16: zfs snapshot pool@a
# get properties of test snaashot pool@a
root@ubuntu16: zfs get guid,createtxg pool@a
NAME    PROPERTY   VALUE      SOURCE
pool@a  guid       8229700390186275401  -
pool@a  createtxg  6          -
# create bookmark pool#a of pool@a
root@ubuntu16: zfs bookmark pool@a pool#a
# try to get bookmark's guid: FAILS WITH ERROR 'invalid dataset name'
# expected: FAILS WITH ERROR 'dataset does not exist' or 'no such pool or dataset'
root@ubuntu16: zfs get guid,createtxg pool#a
cannot open 'pool#a': invalid dataset name
# less efficient workaround:
root@ubuntu16: zfs list -o name,createtxg,guid pool#a
cannot open 'pool#a': invalid dataset name

# module version:
root@ubuntu16: zfs list -t bookmark -r -o name,createtxg,guid pool                                                                                                                                                                                                                                                           
NAME    CREATETXG   GUID
pool#a          6  8229700390186275401
root@ubuntu16: modinfo zfs
filename:       /lib/modules/4.4.0-165-generic/kernel/zfs/zfs/zfs.ko
version:        0.6.5.6-0ubuntu28
license:        CDDL
author:         OpenZFS on Linux
description:    ZFS
srcversion:     99F1D0FED2F291CA7AED0C6
depends:        spl,znvpair,zunicode,zcommon,zavl
retpoline:      Y
vermagic:       4.4.0-165-generic SMP mod_unload modversions 
...
```

Feel free to open an upstream bug (please reference this issue).
However, I doubt this will be fixed because `zfs get ... BOOKMARK` works in newer ZFS versions (and I doubt Canonical is going to backport it to the the 16.04 kmod)

I'll add a ZFS platformtest to detect this issue on other old platforms.

**Closed** 2019-10-14 21:15 UTC
Labels: platform-incompat

**Comment by koffisam** [comment] 2023-06-05 18:05
Hello, 
Is this issue resolved in later versions of zrepl?

We are using `zrepl`  to attempt a backup from an older Ubuntu server to a newer one in sink/pull configuration.

Sink server version details are as follows:
```
cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.7 LTS"
```
The Binary version details
```
modinfo zfs
filename:       /lib/modules/4.4.0-140-generic/kernel/zfs/zfs/zfs.ko
version:        0.6.5.6-0ubuntu26
license:        CDDL
author:         OpenZFS on Linux
description:    ZFS
```

```
zrepl version
client: zrepl version=v0.6.0 go=go1.19.2 GOOS=linux GOARCH=amd64 Compiler=gc
```

Pull server:

```
cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.6 LTS"
```
```
modinfo zfs
filename:       /lib/modules/5.4.0-100-generic/kernel/zfs/zfs.ko
version:        0.8.3-1ubuntu12.13
license:        CDDL
author:         OpenZFS on Linux
```

```
zrepl version
client: zrepl version=v0.6.0 go=go1.19.2 GOOS=linux GOARCH=amd64 Compiler=gc
```
