### ISSUE TITLE
Need non-fatal code from hooks to zrepl to not take snapshot

### ISSUE THREAD

**Issue by reefland** [zrepl/zrepl#715] opened 2023-06-07 15:37 UTC
I have a hook, which checks the filesystems value `written` and if zero do not take a snapshot.  And this is working, but the non-zero return code value sent back to `zrepl` is a VERY spamy fatal error.  I also use `rsyslog` to gather logs from all my systems and the error rate has sky rocketed triggering other alerts.

I propose that a hook return code:
`0` = take snapshot
`1` = do not take snapshot / expected, not an error condition

Any other value can be considered a fatal error (or some form of this).  If a hook is determining if a snapshot should or should not be taken; then there can be valid use cases not to, which should not be considered an error condition.  

I'm requesting the flexibility of sending both signals to `zrepl`.

**Comment by reefland** [comment] 2023-06-08 20:23
To clarify, I did notice the `err_is_fatal: false` under <https://zrepl.github.io/configuration/snapshotting.html#pre-and-post-snapshot-hooks> but based on:

 _`err_is_fatal=false` logs the failed pre-edge invocation but does not affect subsequent hooks nor snapshotting itself._

That setting will still take a snpshot, I'm requesting a non-fatal condition which will not take a snapshot.

**Comment by problame** [comment] 2023-08-26 10:05
I'm closing this request as dupe of #728 . This issue was created earlier but more conversation happened over there.

**Closed by problame** 2023-08-26 10:05 UTC
Labels: feature
